\pagenumbering{arabic}

# Introduction
With the development of experimental techniques suited for omics research, insight in life science increasingly leans on sophisticated data science methodologies to tease apart the complexities of biological systems (Ramos et al. 2017). From the perspective of metabolites as the continuation of the central dogma of molecular biology, metabolomics provides the closest link to phenotype and is thus of special interest, also in multi-omics research (Fiehn 2002).

Untargeted liquid chromatography-mass spectrometry (LC-MS) is the most widely used technique in metabolomics research, largely due to its broad coverage of the metabolome; the small molecules in a biological sample (Gika et al. 2019).  However, due to experimental reasons and the extensive data analysis, it meets challenges with regards to quality and reproducibility (Broadhurst et al. 2018). The Notame protocol article (henceforth referred to as Notame), detailed in the "Metabolomics Data Processing and Data Analysis—Current Best Practices" special issue of the Metabolites journal, presents a contemporary analysis workflow for LC-MS metabolomics data analysis intended for new scholars entering the field (Klåvus et al. 2020). Notame and the R package of the same name specifically accommodates the needs of single-batch, untargeted LC-MS metabolomics data analysis typical of food and nutritional research. Yet, Notame is widely applicable in untargeted LC-MS metabolomics data analysis aiming to gain insight by investigating the metabolic profiles between study groups and time points.

Analysis of omics data is well developed in the R/Bioconductor ecosystem (henceforth referred to as Bioconductor), focused on high-quality open research software for life science (Ramos et al. 2017, Gentleman et al. 2004). Bioconductor can be conceptualized as consisting of data containers, software packages and a community of users and developers, who contribute functionality in a preferrably interoperable fashion. Bioconductor delivers releases consisting of a set of compatible R packages intended for compatibility only within a certain version of R, allowing for reproducible analysis (Gentleman et al. 2004). Use of computational documents is required for documentation in Bioconductor, the broader utility of which is reproducibility. Orchestration of, for example, microbiome transcriptome data analysis with Bioconductor has been explored thoroughly (Lahti et al. 2021). Comparatively, orchestration of untargeted LC-MS metabolomics data analysis with Bioconductor is underdeveloped.

To enhance the quality and reproducibility of untargeted metabolomics data analysis, this thesis aims to implement Notame in a Bioconductor-compatible workflow. No single Bioconductor package provides the functionality needed to implement Notame. Thus, Notame is implemented using a variety of Bioconductor packages. To this end, the space of metabolomics functionality in Bioconductor is explored for implementation of Notame and showcased in an example analysis.

Promoting reproducible, open science is one of the factors identified in the Research Council of Finland’s strategy contributing to the renewal, quality and societal impact of science. To highlight the reproducibility aspect of the thesis, it is written using Quarto, a computational document system which generates an output file of desired format based on text and code input (Allaire et al. 2022).

Capitalizing on the best practices of Notame and the reproducibility of Bioconductor and Quarto, can LC-MS metabolomics data analysis be of higher quality and more reproducible? Can Notame be implemented with Bioconductor using a single data container, given its philosophy of interoperability? Is Notame functionality available but lacks interoperability? Tackling the above questions, the state of Bioconductor functionality with regards to Notame is assessed. A Bioconductor-compatible workflow may promote further development of best practices in Bioconductor and quality, reproducible substantive research efforts. This may ultimately translate to knowledge of complex, biological systems and health outcomes at large.
