# Materials and methods

## Metabolomics functionality in Bioconductor

Packages with functionality relating to LC-MS metabolomics data extraction, data pretreatment, feature selection and biological context under "metabolomics" and "mass spectrometry" in Bioconductor’s BiocViews categorization infrastructure were scrutinized. In other words, packages relating to Notame were included, excluding packages concerned with technical replicates, batch effect and more. Packages that explicitly specified focus on the closely related field of proteomics were excluded to limit the scope of the overview, although they may include relevant functionality as well. Packages utilizing solely original data containers were excluded as it quickly became apparent that they reflect non-interoperable functionality, although interoperability is hard to quantify. Deprecated packages as of Bioconductor version 3.18 were also excluded. Statistical tests, due to their general nature, are included in many packages across modalities, and were not explored systematically in the BiocViews categorization infrastructure. The same holds to a lesser extent for visualizations. Data containers in Bioconductor were also compared non-systematically.

Gaps in Bioconductor functionality were complemented with code in the spirit of not including redundant functionality in Bioconductor, and was made available in GitHub (Suksi 2024). The complementary code was mostly modified from Notame and relies on minimal non-Bioconductor dependencies. The non-Bioconductor dependencies are not concerned with computations which could affect the results. As such, the complementary code can be considered Bioconductor-compatible. Complementary code was written with interoperability and informative naming practices in mind. The Notame documentation is largely applicable.


## Example analysis

The balanced data features 72 fetal brain, intestine and placentae samples from 24 fetuses collected at euthanization of six specific pathogen-free (SPF) and six germ-free (GF) mouse dams just before expected delivery. The data was already collected and preprocessed with MS-DIAL, as per Notame, when the author received it. As such, the example analysis was restricted to data pretreatment and feature selection, the extent of the Notame R package and the functionality covered by the TreeSummarizedExperiment (TSE) data container (see Results section). Restricting to a single data container also makes sense since the Notame best practices are targeted towards new users which may lack programming proficiency. For demonstration purposes, only the first 1000 features included in the data from the HILIC chromatographic column in positive ionization mode was included to reduce execution time and allow for comprehensive visualization of QC and results. The substantive aim of the example analysis was also formulated for demonstrative utility, namely ranking features distinguishing between GF and SPF membership in intestine tissue. In accordance with the emphasis on reproducibility, the example analysis, including implementation details and instructions for rendering, was made available in GitHub (Suksi 2024). The biosigner (Rinaudo et al. 2016), MAI (Dekermanjian et al. 2022), mia (Ernst et al. 2023), phenomis (Thevenot 2023), pmp (Jankevics et al. 2023), POMA (Castellano-Escuder et al. 2021), qmtools (Joo et al. 2023), scater (McCarthy et al. 2017) and QFeatures (Gatto et al. 2023) Bioconductor packages were used in the example analysis.

Low-quality features, having a non-parametric RSD of < 0.2 and non-parametric D-ratio of < 0.4, were flagged. Features detected in less than 70% of the QC samples were removed. QC visualizations were drawn before and after drift correction, excluding flagged features, to inspect the effect of drift correction and as exploratory data analysis.

Features were temporarily nlog-transformed with an offset of one to better meet the assumptions of the smoothed cubic spline model used to normalize for drift. Unfortunately, the drift correction method almost identical to the one in Notame resulted in severely inflated values for many features in an unpredictable manner, so a similar drift correction method by Dunn et al. (2013) was adopted instead. Low-quality features were then flagged anew to inspect the results of drift correction and exclusion of low-quality features.

To complete the abundance matrix, missing values were classified as MCARs/MARs and MNARs and imputed using random forest and a linear regression-based single imputation method, respectively. QC samples were removed before imputation to prevent bias. Imputation was first performed for quality features, followed by imputation of low-quality features. Features were then clustered to reduce the redundant representation of the same metabolite. Each cluster was aggregated by the sum of the cluster in each sample. The resulting features were named and flagged in the order they appeared in the dataset, assuming that highly correlated features are of similar quality.

Samples of all tissue types were needed for drift correction and QC despite the substantive aim of the example analysis only pertaining to intestine tissue. The imputed and clustered set was used without further normalization, transformation or scaling for univariate analysis. A non-parametric test, Mann-Whitney U-test, was used as there were only 12 intestine samples per study group. P-values were adjusted using the Benjamin-Hochberg false discovery rate (FDR) approach to correct for multiple testing where, on average, a significance threshold of 0.05 for twenty tests would give a false positive for one test.

Before supervised learning, the dataset was nlog-transformed to reduce heteroscedasticity and skewness and normalized for dilution with PQN. Random forest was then used for selecting a subset of features with respect to binary classification performance on GF/SPF membership, emphasizing a minimal, stable signature.

The supervised signature was not ranked, but tiered. Features within tiers were ranked according to fold-change to obtain supervised ranks. The univariate and supervised ranks were then combined and forced to increments of one, with any ties resolved simply by the order in which they appeared in the dataset. Features excluded from the supervised signature were ranked separately, and forced to rank after the combined ranks.
