# Discussion

As a relatively new technology, LC-MS research could do well with increased quality and reproducibility, which was attempted here by operationalizing Notame, Bioconductor and Quarto in a Bioconductor-compatible workflow. From a substantive perspective, this would allow science to converge more efficiently on how the metabolome relates to physiology and pathology alike. This, in turn, could inform quality targeted research, ultimately resulting in diagnostics and treatments.

Preprocessing and functionality related to biological context could not be implemented using TSE. It has come to the authors attention that a SE plug-in to MS-DIAL is being explored, which could streamline a Bioconductor-compatible workflow further by MS-DIAL outputting a SummarizedExperiment object directly. Then again, especially preprocessing packages are very developed with unique data containers, and apart from interoperability, it is not obvious what SE could bring to the table.

With the complementary code, data pretreatment could be implemented using TSE as per Notame with minimal deviations. Unfortunately, the QSRSC function in the pmp package, which is almost identical to the drift correction method used in Notame, produced severely inflated values for many features in an unpredictable manner, so a similar drift correction method by Dunn et al. (2013) in the qmtools package was adopted instead. Dunn et al. (2013) did not find a notable performance difference to the method used herein. Imputation using mechanism-aware imputation using random forest for MCARs and single imputation for MNARs is a good example of how Bioconductor can cater to evolving best practices. The third type of missing value, MAR, was not dealt with explicitly, but was rather imputed as an MCAR (Dekermanjian et al. 2023). The clustering method differed from Notame in that the feature clustering used herein ended at filtering of features by correlation in an undirected graph for each retention time window. The correlation method also differed. One can speculate usage of the non-parametric Spearman’s correlation reduces the need for the recursive clustering used in the Notame method as modeling the monotonic relationship of a feature across samples may better distinguish between features originating from the same metabolite, especially if the correlation threshold is optimized. However, neither Notame nor the qmtools package specifies a systematic approach for optimizing the parameters, so it is difficult to compare the methods in a dispassionate manner. Moreover, there is scant discussion in the literature on this approach to feature clustering. Another difference to Notame was the choice of abundance values to represent the clusters. Retaining the sum of the clusters for each sample seems reasonable and is not obviously a downgrade from Notame, where the feature with the highest median abundance is retained. The variety of options for eliminating features from the initial grouping in the qmtools package could prove useful in development and wide adoption of such feature clustering methods.

Feature selection functionality, as per Notame, is somewhat lacking in Bioconductor, especially with regards to linear mixed models and supervised learning. Repeated measures designs of various randomizations are prevalent in metabolomics studies to assess an intervention, necessitating flexible linear mixed models. Flexible linear mixed models or generalized linear mixed models could prove a useful contribution to Bioconductor, especially using SE or TSE. Biosigner was chosen for supervised learning in the example analysis for its emphasis on a restricted, stable set of features for biomarker discovery (Rinaudo et al. 2016). A restricted set of features for pathway analysis, as per the "mid" model in the MUVR package (Shi et al. 2019), could prove a useful contribution to Bioconductor, especially with multilevel classification, minimally biased variable selection, class-specific variable importance and SE-support.

The lack of some functionality in Bioconductor may reflect the lack of a need, putting into question the rationale of a Bioconductor-compatible workflow. From this perspective, a Bioconductor-compatible workflow may seem like an exercise in futility. This is supported in that the Bioconductor-compatible workflow using TSE was not very streamlined due to different coding practices in packages, especially compared to the Notame R package. The TSE lineage-specific functionalities were also not of obvious utility herein, except for addition of alternative feature sets. If Bioconductor released guidelines for coding practices, perhaps separately for modalities, packages might be written to leverage the philosophy of interoperability and functionalities of data containers. Moreover, the availability of relevant functionality supporting TSE in Bioconductor is promising for development of best practices. One must also not overlook Bioconductor's provenance, quality control and documentation.

Regarding provenance and reproducibility, using Quarto covers the reporting standards set forth by DAWG with ease. The utility of Quarto would be emphasized in a fully programmatic workflow including preprocessing and functionality related to biological context. However, the feasibility of tracking provenance so meticulously in a research context is arguable, as there is a substantial amount of work involved in preparing the documents, especially if the research article itself is rendered using Quarto. Some functionality is also missing in Quarto, such as alternative text for figures. Assessing the variability of results in support of replicability may also not be tractable due to the considerable, overnight execution times on a personal computer. Although the research objectives were largely met, this exploration, operationalization and discussion of using Notame, Bioconductor and Quarto points to issues with feasibility.
