# Conclusion

In the spirit of quality and reproducible science, Notame, Bioconductor and Quarto were operationalized in a Bioconductor-compatible workflow spanning data pretreatment and feature selection, the extent of TSE functionality. Feature selection presents limitations of the Bioconductor-compatible workflow. Notame reflects a consensus in the literature, but LC-MS metabolomics data analysis is developing quickly, especially with regards to feature selection. Given Bioconductor's philosophy of interoperability, Bioconductor could accommodate varied research needs and the further development of best practices. However, the rationale of a Bioconductor-compatible workflow is not evident. The purported interoperability of Bioconductor packages proved lackluster, so the Bioconductor-compatible workflow is not as streamlined as expected. The provenance, quality control and documentation of Bioconductor are of more obvious utility, promoting reproducibility. Reproducibility is also promoted by using Quarto, although research culture would have to shift considerably to normalize sharing of data and tracking of provenance so meticulously. The same holds for assessing the variability of results in support of replicability.

As such, it is not straightforward to assess the significance of this thesis in a dispassionate manner, although it is safe to say that it promotes reproducible, open science as per the Research Council of Finland's strategy contributing to the renewal, quality and societal impact of science. Discounting the issues raised above, this demonstration of the utility of Notame, Bioconductor and Quarto may facilitate quality substantive research efforts in tackling question relating the metabolome to complex, biological systems in a reproducible fashion. This could ultimately translate to health outcomes at large. In accordance with the emphasis on reproducibility, the thesis along with instructions for rendering was made available in GitHub (Suksi 2024).
