# Främjande av oriktad LC-MS metabolomikdataanalys med Bioconductor

Utveckling av högeffektiva experimentella tekniker har lagt grunden för forskning i komplexa, biologiska system med hjälp av sofistikerade dataanalyser. Analys av metabolomet, det vill säga de småmolekyler som påträffas i ett biologiskt prov, är speciellt lovande eftersom metabolomet utgör den nivå i molekylärbiologins centrala dogma som mest direkt påverkar fenotypen. Därför är metabolomik centralt för såväl diagnos som vård av sjukdomar med komplex etiologi för vilka orsaksförhållanden inte kan reduceras till exempelvis en enda gen. Metabolomikdata kan även inkluderas i multi-omikanalyser där data från flera olika molekylärbiologiska nivåer används, såsom en TV-apparat med bättre resolution.

Oriktad vätskekromatografi-masspektrometri (eng. untargeted liquid chromatography-mass spectrometry, LC-MS) är en central experimentell teknik i metabolomik, där man strävar efter relativ kvantifiering av alla metaboliter i ett prov. I LC-MS separeras först metaboliterna i ett prov enligt fysisk-kemiska egenskaper i en kromatografikolumn, vartefter metaboliterna joniseras för kvantifiering i en masspektrometer. Jonerna kan även fragmenteras för att åtskilja metaboliter som eluerats ur kromatografikolumnen samtidigt. För att förbättra elueringen av metaboliter med varierande fysisk-kemiska egenskaper genomförs datainsamlingen ofta med flera kromatografikolumner, vartefter rådatan bearbetas för att erhålla data med alla metaboliter som kunde kvantifieras i provet. Datan är vid detta lag inte ännu redo för statistisk analys. Variablerna kan inte antas representera individuella metaboliter, och det förekommer drev i kvantifieringen samt saknande värden. Dessutom måste variablerna genomgå kvalitetskontroll. Före datan är färdig för statistisk analys utförs ännu någon kombination av normalisering, transformation eller skalning beroende på de statistiska metoder som används. Såsom bearbetningen och förbehandlingen, så ock är den statistiska analysen samt den algoritmiska placeringen av resultaten i biologisk kontext extensiv.

Den extensiva dataanalysen utgör en utmaning för reproducerbarhet: den involverade mjukvaran måste rapporteras och fungera för att resultaten kan bestyrkas av tredje parter. Att utföra dataanalysen med ett programmeringsspråk som R är fördelaktigt, eftersom analysen kan då i princip köras om mycket lätt. Å andra sidan används R vanligtvis med en mélange av olika så kallade paket, varav det finns flera versioner och grader av uppdatering och kvalitetskontroll. Detta komplicerar både utförandet av dataanalysen samt reproducering eftersom paketen ofta inte är kompatibla med varandra, eller kan ge olika resultat beroende på version. Bioconductor, ett slags centraliserat arkiv för R-paket, kommer årligen ut med uppsättningar av interkompatibla paket som genomgår kvalitetskontroll. Dessutom är det lätt att rapportera dataanalysen om man använt Bioconductor-paket eftersom versionerna av paketen inte behöver specificeras; istället rapporterar man helt enkelt Bioconductor-versionen och de paket man använt. Reproducerbarhet kan främjas ytterligare med hjälp av beräkningsdokument, där kod, programmatiska resultat såsom figurer och text blandat framställs i ett önskat format, t.ex. som en pdf-fil. Detta försäkrar att de resultat man presenterar säkert härstammar från de rapporterade dataanalysstegen. Dessutom kan en tredje part manipulera dataanalysens parametrar i beräkningsdokumentet och framställa resultaten för att forma en bild över hur robust forskningen är.

En ytterligare utmaning i anslutning till den extensiva dataanalysen är bristen på brett tillämpade goda praxis, vilket leder till forskningsresultat av varierande kvalitet. Rapporteringsstandarder för oriktad LC-MS dataanalys har rekommenderats av Metabolomics Standards Initiative. För bästa praxis har ingen instans gett rekommendationer, men en bra början finns i Notame R-paketet, associerat med en vetenskaplig artikel från en serie artiklar som uttryckligen fokuserar på bästa praxis för oriktad LC-MS dataanalys.

I detta pro gradu-projekt använder jag mig av Bioconductor, beräkningsdokumentmjukvara vid namn Quarto och bästa praxis från Notame för att demonstrera en exempeldataanalys som förespråkar för reproducerbarhet och ökad kvalité av oriktad LC-MS dataanalys. Detta är i linje med öppen vetenskap som är en av de strategiska faktorer Finlands Akademi identifierat för att främja vetenskapens förnyelse, kvalitet och samhälleliga genomslag. Dessutom kan projektet utgöra en startpunkt för fortsatt utveckling av goda praxis i oriktad LC-MS dataanalys med hänsyn till reproducerbarhet.

Det var möjligt att implementera alla programmatiska steg, dvs. Notame R-paketet, i Bioconductor med minimala avvikelser. Dessutom kunde allt implementeras med en enda databehållare, SummarizedExperiment. Notame R-paketet omfattar inte alla steg i oriktad LC-MS dataanalys: bearbetning av rådata och algoritmisk placering i biologisk kontext rekommenderas göras med hjälp av "peka-och-klicka"-mjukvara i Notame-artikeln, trots att även dessa steg finns tillgängliga i Bioconductor.

Oriktad LC-MS används ofta för utforskande forskning som inte betyngs av fasta hypoteser. Detta innebär att hypotestestning i oriktad LC-MS inte handlar om att modellera biologiska faktum, utan att generera hypoteser för bekräftande forskning. Således är dataanalysens kvalitet inte nödvändigtvis lika kritisk som i bekräftande forskning, men påverkar i förlängningen bekräftande forskning. I och med projektet är oriktad LC-MS bättre anpassat för att generera hypoteser av hög kvalitet på ett reproducerbart sätt. Detta kunde bidra till realisering av de förhoppningar vetenskapssamfundet har för maskininlärningsbaserad metabolomik- och multi-omikforskning, speciellt gällande diagnostik och vård av komplexa sjukdomar såsom Alzheimers, diabetes och cancer.
